name: Gridka
options:
  bundleIdPrefix: com.gridka
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    CODE_SIGN_STYLE: Automatic
    ENABLE_HARDENED_RUNTIME: YES
targets:
  Gridka:
    type: application
    platform: macOS
    sources:
      - path: Sources
      - path: Resources
        buildPhase: resources
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.ceesaxp.gridka.app
        INFOPLIST_FILE: Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Gridka.entitlements
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Bridging/Gridka-Bridging-Header.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries"
        OTHER_LDFLAGS:
          - "-lduckdb"
          - "-lc++"
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
          - "$(PROJECT_DIR)/Libraries"
    dependencies:
      - target: GridkaQuickLook
        embed: true
    postCompileScripts:
      - script: |
          mkdir -p "${BUILT_PRODUCTS_DIR}/Gridka.app/Contents/Frameworks"
          cp -f "${PROJECT_DIR}/Libraries/libduckdb.dylib" "${BUILT_PRODUCTS_DIR}/Gridka.app/Contents/Frameworks/libduckdb.dylib"
          if [ -n "${CODE_SIGN_IDENTITY:-}" ] && [ "${CODE_SIGN_IDENTITY}" != "-" ]; then
            codesign --force --sign "${CODE_SIGN_IDENTITY}" --options runtime "${BUILT_PRODUCTS_DIR}/Gridka.app/Contents/Frameworks/libduckdb.dylib"
          fi
        name: Copy and Sign DuckDB dylib
        inputFiles:
          - "$(PROJECT_DIR)/Libraries/libduckdb.dylib"
        outputFiles:
          - "$(BUILT_PRODUCTS_DIR)/Gridka.app/Contents/Frameworks/libduckdb.dylib"
  GridkaQuickLook:
    type: app-extension
    platform: macOS
    sources:
      - path: QuickLookExtension
        excludes:
          - Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: org.ceesaxp.gridka.app.quicklook
        PRODUCT_NAME: GridkaQuickLook
        CODE_SIGN_ENTITLEMENTS: GridkaQuickLook.entitlements
        INFOPLIST_FILE: QuickLookExtension/Info.plist
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SKIP_INSTALL: YES
  GridkaTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: Gridka
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gridka.app.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Gridka.app/Contents/MacOS/Gridka"
        BUNDLE_LOADER: "$(TEST_HOST)"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries"
