name: Gridka
options:
  bundleIdPrefix: com.gridka
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  Gridka:
    type: application
    platform: macOS
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gridka.app
        INFOPLIST_GENERATION_MODE: GeneratedByXcode
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_OBJC_BRIDGING_HEADER: Sources/Bridging/Gridka-Bridging-Header.h
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries"
        LIBRARY_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries"
        OTHER_LDFLAGS:
          - "-lduckdb"
          - "-lc++"
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
          - "$(PROJECT_DIR)/Libraries"
    postCompileScripts:
      - script: |
          mkdir -p "${BUILT_PRODUCTS_DIR}/Gridka.app/Contents/Frameworks"
          cp -f "${PROJECT_DIR}/Libraries/libduckdb.dylib" "${BUILT_PRODUCTS_DIR}/Gridka.app/Contents/Frameworks/libduckdb.dylib"
        name: Copy DuckDB dylib
        inputFiles:
          - "$(PROJECT_DIR)/Libraries/libduckdb.dylib"
        outputFiles:
          - "$(BUILT_PRODUCTS_DIR)/Gridka.app/Contents/Frameworks/libduckdb.dylib"
  GridkaTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: Gridka
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.gridka.app.tests
        GENERATE_INFOPLIST_FILE: YES
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Gridka.app/Contents/MacOS/Gridka"
        BUNDLE_LOADER: "$(TEST_HOST)"
        HEADER_SEARCH_PATHS:
          - "$(PROJECT_DIR)/Libraries"
